version: '3'

services:
    app_healtcheck:
        image: dalozz/app_healtcheck
        environment:
            - PORT_APP=8081
            - driver=oracle.jdbc.driver.OracleDriver
            - username=APP_LMBASE
            - password=CqfAWJoYu3yh
            - url=jdbc:oracle:thin:@host.docker.internal:1521:ORCL
        ports:
            - "8081:8081"
        