# propiedades para entorno desarrollo
# spring.profiles.active=dev
server:
  port: ${PORT_APP}
  servlet:
    context-path: /app  

#Configurando el dataSource
spring:
  datasource:
    name: db
    username: ${username}
    password: ${password}
    url: ${url}
    driver-class-name: ${driver}
    
    

springdoc:
  swagger-ui:
    path: /